### ISSUE TITLE
The container is taking to much height

### ISSUE THREAD

**Issue by shashankdeep** [abhishek305/react-carousel-component#1]
When applying with my cards it is taking to much height how to reduce its height?
@abhishek305 
![Annotation 2020-07-10 153945](https://user-images.githubusercontent.com/58157399/87143483-ca7fb600-c2c3-11ea-9cfc-a8759048862a.png)

**Comment by shashank2209** [comment]
![Annotation 2020-07-10 153945](https://user-images.githubusercontent.com/58157399/87143374-9c01db00-c2c3-11ea-861b-7205d4c4c271.png)

**Comment by shashankdeep** [comment]
done
